version: '3'
services:
  app:
    build: .
    command: ['sleep', 'inf']
    environment:
    - AWS_ACCESS_KEY_ID=xxx
    - AWS_SECRET_ACCESS_KEY=xxx
    - AWS_DEFAULT_REGION=ap-northeast-1
    - USER_TABLE_NAME=dev_user_table
    - DDB_LOCAL_HOST=http://dynamodb:8081
    - PYTHONPATH=/opt
    volumes:
    - ./app:/opt/app
    - ./test:/opt/test
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /ddb-data  -port 8081
    environment:
    - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./ddb-data:/ddb-data
    ports:
    - 8081:8081
  dynamodb-admin:
    image: instructure/dynamo-local-admin
    links:
    - dynamodb 
    environment:
    - DYNAMO_ENDPOINT=http://dynamodb:8081
    - AWS_DEFAULT_REGION=ap-northeast-1
    ports:
    - 8000:8000
